---
- name: "Resouce Groups Deployements"
  hosts: localhost
  connection: local
  tasks:
     - name: "Start-up Resource Group"
       azure_rm_resourcegroup:
         name: 
         location: 
         state: present
     - name: "Production Resource Group"
       azure_rm_resourcegroup:
         name: 
         location: 
         state: present
     - name: "Development Resource Group"
       azure_rm_resourcegroup:
         name: 
         location: 
         state: present

- name: "Deployement of Reservoir Configurations"
  hosts: localhost
  connection: local
  tasks:
     - name: "Production SQL Server"
       azure_rm_sqlserver:
         subscription_id: 
         resource_group: 
         name: 
         location: 
         admin_username: 
         admin_password: 
         version: 12.0
         state: present
         tags:
           tags:
            Env : 
     - name: "Production SQL Server Firewall Rule"
       azure_rm_sqlfirewallrule:
         resource_group: 
         server_name: datahub-prod
         name: 
         start_ip_address: IPADDR
         end_ip_address: IPADDR
     - name: "Production SQL Database"
       azure_rm_sqldatabase:
         subscription_id: 
         resource_group: 
         location: 
         name: reservoir-prod
         server_name: datahub-prod
         force_update: yes
         state: present
         zone_redundant: no
         tags:
            Env: 

     - name: "Development SQL Server"
       azure_rm_sqlserver:
         subscription_id: 
         resource_group: 
         name: datahubdev
         location: 
         admin_username: 
         admin_password: 
         version: 12.0
         state: present
         tags:
            Env : 
     - name: "Development SQL Server Firewall Rule"
       azure_rm_sqlfirewallrule:
         resource_group: 
         server_name: datahubdev
         name: 
         start_ip_address: IPADDR
         end_ip_address: IPADDR
     - name: "Development SQL Database"
       azure_rm_sqldatabase:
         subscription_id: 
         resource_group: 
         location: 
         name: reservoir-dev
         server_name: datahubdev
         force_update: yes
         state: present
         zone_redundant: no
         tags:
            Env: 


- name: "Create Storage Accounts"
  hosts: localhost
  connection: local
  tasks:
     - name: "Primary Storage Account"
       azure_rm_storageaccount:
         subscription_id: 
         resource_group: 
         name: datahubsa
         location: 
         kind: StorageV2
         account_type: Standard_RAGRS
         access_tier: Hot
         state: present
         tags:
            Env: 
     - name: "Container:eventhub"
       azure_rm_storageblob:
         subscription_id: 
         resource_group: 
         storage_account_name: datahubsa
         container: eventhub
         blob_type: block
         force: no
         state: present
     - name: "Container:event-grid-dead-letters"
       azure_rm_storageblob:
         subscription_id: 
         resource_group: 
         storage_account_name: datahubsa
         container: event-grid-dead-letters
         blob_type: block
         force: no
         state: present
     - name: "Container:reservoir-backups"
       azure_rm_storageblob:
         subscription_id: 
         resource_group: 
         storage_account_name: datahubsa
         container: eventhub
         blob_type: block
         force: no
         state: present

     - name: "Secondary Storage Account"
       azure_rm_storageaccount:
         subscription_id: 
         resource_group: 
         name: datahubsitedata
         location: 
         kind: StorageV2
         account_type: Standard_RAGRS
         access_tier: Hot
         state: present

- name: "Event Hub Configurations"
  hosts: localhost
  connection: local
  vars:
    resource_group: 
    location: 
    namespacename: datahub1
    eventhubname: evh-datahub-ignition-prod
  tasks:
    - name: "EventHub Namespace"
      azure_rm_resource:
        api_version: '2017-04-01'
        resource_group: "{{ resource_group }}"
        provider: eventhub
        resource_type: namespaces
        resource_name: "{{ namespacename }}"
        body:
          location: "{{ location }}"
          sku:
            name: Basic
            tier: Basic
            capacity: 10
          properties:
            isAutoInflateEnabled: False
    - name: "Wait-State for Namespace"
      azure_rm_resource_info:
        api_version: '2017-04-01'
        resource_group: "{{ resource_group }}"
        provider: eventhub
        resource_type: namespaces
        resource_name: "{{ namespacename }}"
      register: output
      until: output.response[0].properties.status == 'Active'
      delay: 30
    - debug:
        var: output
    - name: "EventHub"
      azure_rm_resource:
        api_version: '2017-04-01'
        resource_group: "{{ resource_group }}"
        provider: eventhub
        resource_type: namespaces
        resource_name: "{{ namespacename }}"
        subresource:
          - type: eventhubs
            name: "{{ eventhubname }}"
        body:
          location: "{{ location }}"
          properties:
            messageRetentionInDays: 1

- name: "Function App Deployment"
  connection: local
  hosts: localhost
  tasks:
    - name: "AppService"
      azure_rm_appserviceplan:
        subscription_id: 
        resource_group: 
        name: LinuxDynamicPlann
        location: 
        is_linux: yes
        sku: Y1
        number_of_workers: 1
        state: present
    - name: "Function App"
      azure_rm_functionapp:
        subscription_id: 
        resource_group: 
        name: datahub-harnesss
        location: 
        storage_account: datahubsa
        plan: LinuxDynamicPlan
        state: present
        tags:
            Env : 

- name: "Deployment of Log Analytics Workspace"
  connection: local
  hosts: localhost
  tasks:
    - name: "Log Analytics Workspace"
      azure_rm_loganalyticsworkspace:
        subscription_id: 
        resource_group: 
        location: 
        name: log-datahubb-prod
        sku: standard
        state: present
        retention_in_days: 30
        intelligence_packs:
          Backup: true
        tags:
            Env : 

#SERVICES FOR FUTURE USE.

- name: "WebApp Deployment"
  hosts: localhost
  connection: local
  vars:
    resource_group_webapp: 
    resource_group: 
    webapp_name: dhwbap
    plan_name: dhservpln
    location: 
    traffic_manager_profile_name: ApexDHTrafficManagerProfile
    traffic_manager_endpoint_name: ApexDHTrafficManagerEndpoint
  tasks:
  - name: "App Service Plan"
    azure_rm_appserviceplan:
      resource_group: "{{ resource_group }}"
      name: "{{ plan_name }}"
      location: "{{ location }}"
      is_linux: true
      sku: S1
      number_of_workers: 1

  - name: "App Service (WebApp)"
    azure_rm_webapp:
        resource_group: "{{ resource_group_webapp }}"
        name: "{{ webapp_name }}"
        plan:
          resource_group: "{{ resource_group }}"
          name: "{{ plan_name }}"
          is_linux: true
          sku: S1
          number_of_workers: 1
        app_settings:
          testkey: "testvalue"
        frameworks:
          - name: java
            version: 8
  - name: "Get web app facts"
    azure_rm_webapp_facts:
      resource_group: "{{ resource_group_webapp }}"
      name: "{{ webapp_name }}"
    register: webapp
  - name: "Traffic Manager Profile"
    azure_rm_trafficmanagerprofile:
      resource_group: "{{ resource_group_webapp }}"
      name: "{{ traffic_manager_profile_name }}"
      location: global
      routing_method: performance
      dns_config:
        relative_name: "{{ traffic_manager_profile_name }}"
        ttl:  60
      monitor_config:
        protocol: HTTPS
        port: 80
        path: '/'
  - name: "Adding endpoint to traffic manager profile."
    azure_rm_trafficmanagerendpoint:
      resource_group: "{{ resource_group_webapp }}"
      profile_name: "{{ traffic_manager_profile_name }}"
      name: "{{ traffic_manager_endpoint_name }}"
      type: azure_endpoints
      location: "{{ location }}"
      target_resource_id: "{{ webapp.webapps[0].id }}"

- name: "Virtual Machine Deployment"
  connection: local
  hosts: localhost
  tasks:
  - name: "Resource Group"
    azure_rm_resourcegroup:
      name: ResourceGroup
      location: 
  - name: "Virtual Network"
    azure_rm_virtualnetwork:
      resource_group: ResourceGroup
      name: Vnet
      address_prefixes: "IPADDR"
  - name: "Subnet"
    azure_rm_subnet:
      resource_group: ResourceGroup
      name: Subnet
      address_prefix: "IPADDR"
      virtual_network: Vnet
  - name: "Public IP Address"
    azure_rm_publicipaddress:
      resource_group: ResourceGroup
      allocation_method: Static
      name: PublicIP
    register: output_ip_address
  - name: "Show Public  IP of VM"
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: "Network Security Group for SSH"
    azure_rm_securitygroup:
      resource_group: ResourceGroup
      name: NetworkSecurityGroup
      rules:
        - name: 
          protocol: 
          destination_port_range: 
          access: Allow
          priority: 
          direction: Inbound
  - name: "Virtual network interface card"
    azure_rm_networkinterface:
      resource_group: ResourceGroup
      name: NIC
      virtual_network: Vnet
      subnet: Subnet
      public_ip_name: PublicIP
      security_group: NetworkSecurityGroup
  - name: "Virtual Machine"
    azure_rm_virtualmachine:
      resource_group: ResourceGroup
      name: VM
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      admin_password: 
      network_interfaces: NIC
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
